// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_QnXIEMs9pE3AiDbEaOLuESbdhSXBY6I',
    appId: '1:788536548988:web:bc4aa0289b9b0b233db3f9',
    messagingSenderId: '788536548988',
    projectId: 'unitrail-db9e1',
    authDomain: 'unitrail-db9e1.firebaseapp.com',
    storageBucket: 'unitrail-db9e1.appspot.com',
    measurementId: 'G-2SR1H496DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHkz7qLR__edXJJUljDNcJXEWgTWkdgo4',
    appId: '1:788536548988:android:1644d35c919f4cf23db3f9',
    messagingSenderId: '788536548988',
    projectId: 'unitrail-db9e1',
    storageBucket: 'unitrail-db9e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL7WOKx000ZqzGhsKewyL-wpBd7-sQae0',
    appId: '1:788536548988:ios:ba3c654e22becb1f3db3f9',
    messagingSenderId: '788536548988',
    projectId: 'unitrail-db9e1',
    storageBucket: 'unitrail-db9e1.appspot.com',
    iosClientId: '788536548988-dm79og29vcdiipem4ordj4q3hb3j4hpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.unitrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL7WOKx000ZqzGhsKewyL-wpBd7-sQae0',
    appId: '1:788536548988:ios:ba3c654e22becb1f3db3f9',
    messagingSenderId: '788536548988',
    projectId: 'unitrail-db9e1',
    storageBucket: 'unitrail-db9e1.appspot.com',
    iosClientId: '788536548988-dm79og29vcdiipem4ordj4q3hb3j4hpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.unitrail',
  );
}
